version: '3.8'

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      - ./scripts:/scripts

    # Overrides default command so things don't shut down after the process ends.
    command: sh -c "/scripts/cassandra-setup.sh && sleep infinity"

    # Runs db-mysql on the same network as the db containers, allows "forwardPorts" in devcontainer.json function.
    networks:
      - app-network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - db-mysql

  db-mysql:
    hostname: db-mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}